apiVersion: v1
kind: Service
metadata:
    name: "nbaks009-a2b0"
    labels:
        app: "nbaks009-a2b0"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "nbaks009-a2b0"